### ISSUE TITLE
Vietnamese corpus size 6616 pairs, not 19K? 

### ISSUE THREAD

**Issue by datquocnguyen** [esdurmus/Wikilingua#1]
Hi, thanks a lot for your nice work.

I downloaded the Vietnamese dataset `vietnamese.pkl`. 

I found that there are only 6616 summary and document pairs (i.e. wikihow links) in the dataset. But you show in your paper and the Readme file that there are 19K summary and document pairs. 

Do you consider each article section as document? Could you please clarify this?

Thank you.
Best,
Dat.

**Comment by esdurmus** [comment]
Hi, 

For Vietnamese, 6,616 corresponds number of webpages. However, if you at the dictionary, there are multiple sections per page. If you count number total sections and corresponding summaries, you can see that there are 19,600 examples. 

We structured it this way so that it is clear which sections belong to the same WikiHow page. Note that in our dataset, sections corresponds to input documents. Having this information is important. For instance, in our case, when creating train/dev/test splits, we made sure that sections from the same pages are are mapped to the same split. 

I hope this clears it up. Feel free to reach out if it is not clear.

**Comment by datquocnguyen** [comment]
Thanks for your clarification.
